[tack]
recomposable = true

[inputs.adios]
url = "github:llakala/lladios"
type = "fetch"

[inputs.nixpkgs]
url = "github:NixOS/nixpkgs/nixpkgs-unstable"
type = "fetch"

[inputs.now]
url = "git+https://codeberg.org/now-runner/now.git"
type = "fetch"
